[package]
name = "pakket-core"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = { version = "1.0.16", features = ["serde"] }
directories = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"
